### ISSUE TITLE
Add Firebase (angular-fire)

### ISSUE THREAD

**Issue by thrashtechinfo** [thrashtechinfo/chatify#12]
Add **angular-fire** in the app.
Perform **Firebase CRUD** using sample users-service.
Maintain **Readme.md** file

**Comment by muhammadawaisshaikh** [comment]
I want to contribute to this. please assign it to me.

**Comment by thrashtechinfo** [comment]
@muhammadawaisshaikh you can, let me assign it to you. #happyCoding
