### ISSUE TITLE
Implement User's search in chat module like whatsapp

### ISSUE THREAD

**Issue by thrashtechinfo** [thrashtechinfo/chatify#13]
1. under **chat module** there's some component with Chat or some other name
2. UI will be implemented first - **_Prerequisite_**
3. UI have two sections like **whatsapp** (right+left)
4. Right section > **_Users Listing_**
5. Left Section > **_Chat of selected User from right section_**

> Implement Search on Right Section

**Comment by puneetsaluja100** [comment]
Hi, I am interested to work on this functionality.

**Comment by thrashtechinfo** [comment]
go ahead, I will wait for your clean and healthy PR 💯 👍 @puneetsaluja100
