### ISSUE TITLE
add chat module

### ISSUE THREAD

**Issue by thrashtechinfo** [thrashtechinfo/chatify#5]
Add **LazyLoaded** Chat Module with following components:

Chat
Users - list of online/offline users

Note: develop **basic ui** with bootstrap Components

**Comment by puneetsaluja100** [comment]
Can i work on this as well, since i have to start on issue #13

**Comment by thrashtechinfo** [comment]
@puneetsaluja100 sure

**Comment by thrashtechinfo** [comment]
good @puneetsaluja100

**Comment by puneetsaluja100** [comment]
thanks @thrashtechinfo 
Can you please add "hacktoberfest" topic to the repository. So that my pull request is counted,
