### ISSUE TITLE
Http Core functionality

### ISSUE THREAD

**Issue by thrashtechinfo** [thrashtechinfo/chatify#6]
Add the **API** calls **HTTP Resolver** and **config** with following pattern:

- create config service with following directory structure:
core > http > **config-service** (will get the API endpoint from environment file)

- create token interceptor with following directory structure:
core > http > **token-interceptor**

- create a HTTP service of Users
core > http > **users-service** (will consume mock API call to perform users CRUD using config service and token interceptor)

**Comment by kaushik2901** [comment]
Hi, I would love to work on this issue! 
We can discuss about this!
And can you please assign me on this?

**Comment by thrashtechinfo** [comment]
@kaushik2901 sure. you can Fork this Repo and submit the PR, I will review and merge.
